steps:
# Create Chart skeleton
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        mkdir -p knative/templates
        mv Chart.yaml ./knative
        mv values.yaml ./knative
        mv knative-cluster-role.yaml ./knative/templates

# Get the Istio 1.0.7 manifest to resolve CVE-2019-9900 and CVE-2019-9901
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/istio.yaml', 'https://raw.githubusercontent.com/knative/serving/release-0.5/third_party/istio-1.0.7/istio.yaml']

# Get the Knative Build manifest
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/knative-build.yaml', 'https://github.com/knative/build/releases/download/v0.5.0/build.yaml']

# Get the Knative Build/Serving cluster roles
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/knative-build-clusterrole.yaml', 'https://raw.githubusercontent.com/knative/serving/master/third_party/config/build/clusterrole.yaml']

# Get the Knative Serving manifest
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/knative-serving.yaml', 'https://github.com/knative/serving/releases/download/v0.4.1/serving.yaml']

# Templatize the chart
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        cat knative/templates/knative-build.yaml knative/templates/knative-serving.yaml > knative/templates/knative.yaml.base
        rm knative/templates/knative-build.yaml knative/templates/knative-serving.yaml
        sed -i 's/{{/{{ "{{" }}/g' knative/templates/knative.yaml.base
        sed -i 's/example.com/{{ .Values.domain }}/' knative/templates/knative.yaml.base
        sed -i 's/LoadBalancer/{{ .Values.istioIngressType }}/' knative/templates/istio.yaml
        ./fix-knative.pl knative/templates/knative.yaml.base > knative/templates/knative.yaml
        rm knative/templates/knative.yaml.base

# Initialize Helm without Cluster
- name: 'gcr.io/triggermesh/helm'
  args: ['init', '--client-only']

# Install gcs plugin
- name: 'gcr.io/triggermesh/helm'
  args: ['plugin', 'install', 'https://github.com/viglesiasce/helm-gcs.git']

# Package the chart
- name: 'gcr.io/triggermesh/helm'
  args: ['package', 'knative']

# Create repo directory
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        mkdir repo
        mv knative-0.4.1.tgz ./repo

# Retrieve the current index
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', './upstream.yaml', 'https://storage.googleapis.com/triggermesh-charts/index.yaml']

# Generate index
- name: 'gcr.io/triggermesh/helm'
  args: ['repo', 'index', '--merge', './upstream.yaml', '--url', 'https://storage.googleapis.com/triggermesh-charts', './repo']

# Push new index to gcs bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './repo/index.yaml', 'gs://$PROJECT_ID-charts/index.yaml']

# Push it to gcs bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './repo/knative-0.4.1.tgz', 'gs://$PROJECT_ID-charts/knative-0.4.1.tgz']

# Build the installer
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/knative-installer:0.4.1', '-f', './installer/Dockerfile', '.']

# Tag and push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/knative-installer:0.4.1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/knative-installer:0.4.1', 'gcr.io/$PROJECT_ID/knative-installer:0.4']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/knative-installer:0.4']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/knative-installer:0.4.1', 'gcr.io/$PROJECT_ID/knative-installer:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/knative-installer:latest']
