steps:
# Create Chart skeleton
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        mkdir -p knative/templates
        mv Chart.yaml ./knative
        mv values.yaml ./knative

# Get the Istio manifest
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/istio.yaml', 'https://raw.githubusercontent.com/knative/serving/master/third_party/istio-1.0.2/istio.yaml']

# Get the Knative manifest
- name: 'gcr.io/cloud-builders/wget'
  args: ['-O', 'knative/templates/knative.yaml', 'https://github.com/knative/serving/releases/download/v0.1.1/release-no-mon.yaml']

# Templatize the chart
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        sed -i 's/example.com/{{ .Values.domain }}/' knative/templates/knative.yaml

# Initialize Helm without Cluster
- name: 'gcr.io/triggermesh/helm'
  args: ['init', '--client-only']

# Install gcs plugin
- name: 'gcr.io/triggermesh/helm'
  args: ['plugin', 'install', 'https://github.com/viglesiasce/helm-gcs.git']

# Package the chart
- name: 'gcr.io/triggermesh/helm'
  args: ['package', 'knative']

# Create repo directory
- name: 'debian:stable-slim'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        mkdir repo
        mv knative-0.1.3.tgz ./repo

# Generate index
- name: 'gcr.io/triggermesh/helm'
  args: ['repo', 'index', '--url', 'https://storage.googleapis.com/triggermesh-charts', './repo']

# Push index to gcs bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './repo/index.yaml', 'gs://$PROJECT_ID-charts/index.yaml']

# Push it to gcs bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', './repo/knative-0.1.3.tgz', 'gs://$PROJECT_ID-charts/knative-0.1.3.tgz']
